### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by laraveladminpanel**

### CODE REVIEW

**Comment by fletch3555** [comment]
Merging of this PR would constitute violation of Voyager's license and copyright.

**Comment by alexeykostenko** [comment]
Can I add this license below, under the license of The Control Group? I
mean sublicense.

2018-06-07 17:43 GMT+03:00 Eric Fletcher <notifications@github.com>:

**Comment by fletch3555** [comment]
I'm not a lawyer, so I honestly can't answer that.

This license, however, is still MIT, and really doesn't grant you anything differently.

**Comment by alexeykostenko** [comment]
I rewrite the documentation, but it takes three days. Can I leave the
documentation for tree days?

2018-06-07 23:48 GMT+03:00 Eric Fletcher <notifications@github.com>:

**Comment by fletch3555** [comment]
That's fine, so long as you make the effort.

**Pull request closed without merging**
